Update required dependencies
talister/pwv pull request #1
Opened 2018-11-05 16:29 UTC by Siltala

While trying to run the code I noticed that a number of dependencies were missing from both requirements.txt (Python modules) and required non-pip packages (libhdf4-dev, python3-dev and python3-numpy).

This PR adds the missing Python packages to requirements.txt and the rest to README.md. It would perhaps be ideal if numpy was included in requirements.txt but this fails as python-hdf4 will not install, causing the entire pip install command to fail, unless numpy has already been installed beforehand.

At least on my system, the program runs fine with these changes. Let me know if something's wrong here.

2018-11-05 17:16 UTC, talister requested changes
`numpy` is actually pulled in by `astropy` but it would be better to have this explicitly listed in the `requirements.txt` - I prefer to setup virtualenv's with what's needed rather than rely on system python versions (I am developing on CentOS 7 where the system python is 2.7.5)

2018-11-06 13:04 UTC, Siltala commented
Hi,
You're right that astropy does actually also pull in numpy but this doesn't change the problem: at least for me, python-hdf4 will fail to install and the entire `pip3 install -r requirements.txt` command will fail as a result unless numpy is installed -before- everything else, either systemwide or with `pip3 install numpy`.
I'm by no means an expert with pip but this seems like a problem in the python-hdf4 pip installation script itself rather than something on your end.

2018-11-06 17:33 UTC, talister commented
Yes I have seen this with other packages that need `numpy` in that something seems to go wrong in the dependency resolution and the `pip install` falls over in a heap... 
If you could an explicit `pip3 install numpy` to the instructions above the main requirements line in the docs, then I can get this merged in.

2018-11-07 13:19 UTC, Siltala commented
I amended my commit as requested, hopefully it's fine now. Sorry about the delays!

2018-11-08 00:39 UTC, talister approved these changes

2018-11-08 00:39 UTC, merged